### ISSUE TITLE
Breaking Change: AppLifecycleState.suspended

### ISSUE THREAD

**Issue by husmen73** [siddhesh-tamhanekar/media_player#21]
"Breaking change to support the fact that AppLifecycleState.suspended has changed to AppLifecycleState.detached."

Please update your code on /lib/media_player.dart on line 526

**Comment by dimiril** [comment]
up

**Comment by iampato** [comment]
In the mean time just add this to your `pubspec.yaml` file
``` 
media_player:
    git:
      url: git://github.com/stevenosse/media_player.git
```
As we wait for the PR to get merged

**Comment by riskiadi** [comment]
unfortunately this project has been abandoned

**Comment by riskiadi** [comment]
use this on dependencies
```
 media_player:
    git:
      url: git://github.com/Iampato/media_player.git
      ref: androidx
```
